"""
FastAPI router for the AI orchestration engine.

Provides endpoints to inspect engine status, usage stats, recommended
cron schedules, configuration updates, alerts, and reset operations.
"""

from __future__ import annotations

from fastapi import APIRouter, status

from .engine import OrchestrationEngine
from .schemas import (
    AlertsResponse,
    EngineConfigResponse,
    EngineConfigUpdate,
    EngineStatusResponse,
    ResetRequest,
    ResetResponse,
    ScheduleResponse,
    UsageResponse,
)

router = APIRouter(prefix="/api/orchestration", tags=["orchestration"])


# ---------------------------------------------------------------------------
# GET /api/orchestration/status
# ---------------------------------------------------------------------------

@router.get(
    "/status",
    response_model=EngineStatusResponse,
    summary="Current engine status",
    description=(
        "Returns the current orchestration engine state including circuit "
        "breaker status, budget utilisation, rolling metrics, and active model."
    ),
)
async def get_status() -> EngineStatusResponse:
    engine = OrchestrationEngine.get_instance()
    return await engine.get_status()


# ---------------------------------------------------------------------------
# GET /api/orchestration/usage
# ---------------------------------------------------------------------------

@router.get(
    "/usage",
    response_model=UsageResponse,
    summary="Usage statistics",
    description=(
        "Returns AI API usage statistics broken down by hour, endpoint, "
        "and model. Includes recent log entries."
    ),
)
async def get_usage() -> UsageResponse:
    engine = OrchestrationEngine.get_instance()
    return await engine.get_usage()


# ---------------------------------------------------------------------------
# GET /api/orchestration/schedule
# ---------------------------------------------------------------------------

@router.get(
    "/schedule",
    response_model=ScheduleResponse,
    summary="Recommended cron schedule",
    description=(
        "Returns recommended cron job schedules for AI-powered operations "
        "such as Gmail sync, feedback analysis, health score recalculation, "
        "pattern detection, usage reporting, and stale data cleanup."
    ),
)
async def get_schedule() -> ScheduleResponse:
    engine = OrchestrationEngine.get_instance()
    return engine.suggest_schedule()


# ---------------------------------------------------------------------------
# POST /api/orchestration/config
# ---------------------------------------------------------------------------

@router.post(
    "/config",
    response_model=EngineConfigResponse,
    summary="Update engine configuration",
    description=(
        "Update runtime configuration for the orchestration engine. "
        "Supports changing budget limits, loop detection thresholds, "
        "and model defaults."
    ),
)
async def update_config(payload: EngineConfigUpdate) -> EngineConfigResponse:
    engine = OrchestrationEngine.get_instance()
    return await engine.update_config(
        daily_token_limit=payload.daily_token_limit,
        daily_cost_limit_usd=payload.daily_cost_limit_usd,
        loop_max_calls=payload.loop_detection_max_calls,
        loop_window_seconds=payload.loop_detection_window_seconds,
        budget_warning_threshold_pct=payload.budget_warning_threshold_pct,
        default_model=payload.default_model,
        downgrade_model=payload.downgrade_model,
    )


# ---------------------------------------------------------------------------
# GET /api/orchestration/alerts
# ---------------------------------------------------------------------------

@router.get(
    "/alerts",
    response_model=AlertsResponse,
    summary="Recent alerts and warnings",
    description=(
        "Returns recent alerts generated by the orchestration engine "
        "including loop detections, budget warnings, and circuit breaker "
        "state changes."
    ),
)
async def get_alerts() -> AlertsResponse:
    engine = OrchestrationEngine.get_instance()
    return await engine.get_alerts()


# ---------------------------------------------------------------------------
# POST /api/orchestration/reset
# ---------------------------------------------------------------------------

@router.post(
    "/reset",
    response_model=ResetResponse,
    summary="Reset engine state",
    description=(
        "Reset parts of the orchestration engine state. Can reset the "
        "circuit breaker back to CLOSED, clear alerts, and/or clear the "
        "in-memory usage buffer."
    ),
)
async def reset_engine(payload: ResetRequest) -> ResetResponse:
    engine = OrchestrationEngine.get_instance()
    return await engine.reset(
        reset_circuit_breaker=payload.reset_circuit_breaker,
        clear_alerts=payload.clear_alerts,
        clear_usage_buffer=payload.clear_usage_buffer,
    )
